Sf3/PHP7 update
nfq-rho/admin-bundle pull request #4
Opened 2017-01-04 15:25 UTC by kaltun

2017-01-05 06:54 UTC, N3m1s requested changes

2017-01-05 06:54 UTC, N3m1s commented on Form/TranslatableType.php
>  use Symfony\Component\OptionsResolver\OptionsResolverInterface;
`use Symfony\Component\OptionsResolver\OptionsResolverInterface` is not used anymore?

2017-01-05 06:54 UTC, N3m1s commented on Resources/config/services.yml
> +              - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextareaType }
to awoid BC, both, `alias` end `extended_type` should be here

2017-01-05 06:54 UTC, N3m1s commented on composer.json
> -        "symfony/symfony": "~2.3",
Looking at the changes I seems that they would work with Symfony 2.7, 2.8 too, so the version should be 
`"symfony/symfony": "~2.7|~3.0"`

2017-01-05 06:54 UTC, N3m1s commented on composer.json
>          "php": ">=5.4",
The use of `::class` implies that the minimum version for PHP should be 5.5

2017-01-10 06:51 UTC, kaltun commented on Form/TranslatableType.php
>  use Symfony\Component\OptionsResolver\OptionsResolverInterface;
No, OptionsResolverInterface is deprecated.

2017-01-10 06:55 UTC, kaltun commented on composer.json
> -        "symfony/symfony": "~2.3",
changed

2017-01-10 06:57 UTC, kaltun commented on composer.json
>          "php": ">=5.4",
thank you for the notice!!!

2017-01-10 07:01 UTC, kaltun commented on Resources/config/services.yml
> +              - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextareaType }
fixed

2017-01-29 17:22 UTC, N3m1s commented on Form/TranslatableType.php
>  use Symfony\Component\OptionsResolver\OptionsResolverInterface;
So why it is there, in use's??

2017-01-29 23:33 UTC, merged